name: camera_macos
description: macOS camera package implementation. Supports both internal and external cameras, can take pictures and record video with audio as well.
version: 0.0.8
repository: https://github.com/riccardo-lomazzi/camera_macos

environment:
  sdk: '>=2.18.2 <4.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter


# The following section is specific to Flutter packages.
flutter:
  plugin:
    platforms:
      macos:
        pluginClass: CameraMacosPlugin
